### ISSUE TITLE
Compatibility with MCP2518FD

### ISSUE THREAD

**Issue by tpimh** [WMT-GmbH/mcp25xx#1]
MCP2510, MCP2515 and MCP25625 are marked as "Not Recommended for new designs" on Microchip's website. Suggested replacement is [MCP2518FD](https://www.microchip.com/en-us/product/mcp2518fd) which seems mostly compatible while also adding CAN FD support. Has anyone tested it with this driver? Does it work?

**Comment by dimpolo** [comment]
> seems mostly compatible

Do you mean the registers?

Unless I'm misunderstanding something the MCP2518FD seems to have a very different interface.

**Comment by tpimh** [comment]
You are correct. My first impression was that MCP2518FD was meant almost as a drop-in replacement for MCP2515 with additional extra features, however upon closer examination, it is very different. The drivers that support both MCP251x and MCP251xFD usually have two separate implementations for both families. Since I don't need CAN FD, it's much easier to stick with MCP2515.

**Comment by dimpolo** [comment]
Alright :)
Thanks for clarifying!
