### ISSUE TITLE
Add support for MCP251863

### ISSUE THREAD

**Issue by Kerbidiah** [WMT-GmbH/mcp25xx#4]
Hello there!

I was wondering if it would be OK if I make a pull request to add support for the MCP251863. If so, where in the code base should I look to start working on this?

Thank you!
Alex Janninck
_Purdue University_

**Comment by dimpolo** [comment]
Hi Alex,

Thanks for reaching out!

The MCP251863 and similar CAN FD controllers have quite a different interface compared to the CAN controllers currently supported by this crate.

It might make more sense to consider starting a new project or perhaps contributing to [this project](https://crates.io/crates/mcp2517), which is also focused on a CAN FD controller.
